ALTER TABLE users_roles
    ADD CONSTRAINT FK_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    ADD CONSTRAINT FK_role_id FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE;